# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_MasterWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MasterWindow(object):
    def setupUi(self, MasterWindow):
        MasterWindow.setObjectName("MasterWindow")
        MasterWindow.resize(800, 627)
        self.centralwidget = QtWidgets.QWidget(MasterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setObjectName("exitButton")
        self.gridLayout.addWidget(self.exitButton, 5, 8, 1, 1)
        self.deleteAchromatButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteAchromatButton.setObjectName("deleteAchromatButton")
        self.gridLayout.addWidget(self.deleteAchromatButton, 2, 8, 1, 1)
        self.achromatButton = QtWidgets.QPushButton(self.centralwidget)
        self.achromatButton.setObjectName("achromatButton")
        self.gridLayout.addWidget(self.achromatButton, 2, 0, 1, 1)
        self.lensButton = QtWidgets.QPushButton(self.centralwidget)
        self.lensButton.setObjectName("lensButton")
        self.gridLayout.addWidget(self.lensButton, 1, 0, 1, 1)
        self.sourceButton = QtWidgets.QPushButton(self.centralwidget)
        self.sourceButton.setObjectName("sourceButton")
        self.gridLayout.addWidget(self.sourceButton, 0, 0, 1, 1)
        self.editAchromatButton = QtWidgets.QPushButton(self.centralwidget)
        self.editAchromatButton.setObjectName("editAchromatButton")
        self.gridLayout.addWidget(self.editAchromatButton, 2, 7, 1, 1)
        self.editLensButton = QtWidgets.QPushButton(self.centralwidget)
        self.editLensButton.setObjectName("editLensButton")
        self.gridLayout.addWidget(self.editLensButton, 1, 7, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 5, 7, 1, 1)
        self.plotFigure = PlotWidget(self.centralwidget)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.plotFigure.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.plotFigure.setForegroundBrush(brush)
        self.plotFigure.setObjectName("plotFigure")
        self.gridLayout.addWidget(self.plotFigure, 4, 0, 1, 9)
        self.deleteSourceButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteSourceButton.setObjectName("deleteSourceButton")
        self.gridLayout.addWidget(self.deleteSourceButton, 0, 8, 1, 1)
        self.editZemaxButton = QtWidgets.QPushButton(self.centralwidget)
        self.editZemaxButton.setObjectName("editZemaxButton")
        self.gridLayout.addWidget(self.editZemaxButton, 3, 7, 1, 1)
        self.deleteZemaxButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteZemaxButton.setObjectName("deleteZemaxButton")
        self.gridLayout.addWidget(self.deleteZemaxButton, 3, 8, 1, 1)
        self.optimiseButton = QtWidgets.QPushButton(self.centralwidget)
        self.optimiseButton.setObjectName("optimiseButton")
        self.gridLayout.addWidget(self.optimiseButton, 5, 5, 1, 1)
        self.zemaxButton = QtWidgets.QPushButton(self.centralwidget)
        self.zemaxButton.setObjectName("zemaxButton")
        self.gridLayout.addWidget(self.zemaxButton, 3, 0, 1, 1)
        self.writeButton = QtWidgets.QPushButton(self.centralwidget)
        self.writeButton.setObjectName("writeButton")
        self.gridLayout.addWidget(self.writeButton, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 1, 1, 1)
        self.deleteLensButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteLensButton.setObjectName("deleteLensButton")
        self.gridLayout.addWidget(self.deleteLensButton, 1, 8, 1, 1)
        self.endDistanceBox = QtWidgets.QLineEdit(self.centralwidget)
        self.endDistanceBox.setObjectName("endDistanceBox")
        self.gridLayout.addWidget(self.endDistanceBox, 5, 2, 1, 1)
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setObjectName("runButton")
        self.gridLayout.addWidget(self.runButton, 5, 3, 1, 2)
        self.editSourceButton = QtWidgets.QPushButton(self.centralwidget)
        self.editSourceButton.setObjectName("editSourceButton")
        self.gridLayout.addWidget(self.editSourceButton, 0, 7, 1, 1)
        self.settingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingsButton.setObjectName("settingsButton")
        self.gridLayout.addWidget(self.settingsButton, 5, 6, 1, 1)
        self.sourceCombo = QtWidgets.QComboBox(self.centralwidget)
        self.sourceCombo.setObjectName("sourceCombo")
        self.gridLayout.addWidget(self.sourceCombo, 0, 1, 1, 6)
        self.lensCombo = QtWidgets.QComboBox(self.centralwidget)
        self.lensCombo.setObjectName("lensCombo")
        self.gridLayout.addWidget(self.lensCombo, 1, 1, 1, 6)
        self.achromatCombo = QtWidgets.QComboBox(self.centralwidget)
        self.achromatCombo.setObjectName("achromatCombo")
        self.gridLayout.addWidget(self.achromatCombo, 2, 1, 1, 6)
        self.zemaxCombo = QtWidgets.QComboBox(self.centralwidget)
        self.zemaxCombo.setObjectName("zemaxCombo")
        self.gridLayout.addWidget(self.zemaxCombo, 3, 1, 1, 6)
        MasterWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MasterWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MasterWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MasterWindow)
        self.statusbar.setObjectName("statusbar")
        MasterWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MasterWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MasterWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionNew = QtWidgets.QAction(MasterWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionExit = QtWidgets.QAction(MasterWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_As = QtWidgets.QAction(MasterWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MasterWindow)
        QtCore.QMetaObject.connectSlotsByName(MasterWindow)
        MasterWindow.setTabOrder(self.sourceButton, self.lensButton)
        MasterWindow.setTabOrder(self.lensButton, self.achromatButton)
        MasterWindow.setTabOrder(self.achromatButton, self.endDistanceBox)
        MasterWindow.setTabOrder(self.endDistanceBox, self.writeButton)
        MasterWindow.setTabOrder(self.writeButton, self.runButton)
        MasterWindow.setTabOrder(self.runButton, self.exitButton)

    def retranslateUi(self, MasterWindow):
        _translate = QtCore.QCoreApplication.translate
        MasterWindow.setWindowTitle(_translate("MasterWindow", "Raytrace"))
        self.exitButton.setText(_translate("MasterWindow", "Close"))
        self.deleteAchromatButton.setText(_translate("MasterWindow", "Delete Achromat"))
        self.achromatButton.setText(_translate("MasterWindow", "New Achromat"))
        self.lensButton.setText(_translate("MasterWindow", "New Lens"))
        self.sourceButton.setText(_translate("MasterWindow", "New Source"))
        self.editAchromatButton.setText(_translate("MasterWindow", "Edit Achromat"))
        self.editLensButton.setText(_translate("MasterWindow", "Edit Lens"))
        self.saveButton.setText(_translate("MasterWindow", "Save"))
        self.deleteSourceButton.setText(_translate("MasterWindow", "Delete Source"))
        self.editZemaxButton.setText(_translate("MasterWindow", "Edit Zemax"))
        self.deleteZemaxButton.setText(_translate("MasterWindow", "Delete Zemax"))
        self.optimiseButton.setText(_translate("MasterWindow", "Optimise"))
        self.zemaxButton.setText(_translate("MasterWindow", "New Zemax"))
        self.writeButton.setText(_translate("MasterWindow", "Write"))
        self.label.setText(_translate("MasterWindow", "End Point"))
        self.deleteLensButton.setText(_translate("MasterWindow", "Delete Lens"))
        self.runButton.setText(_translate("MasterWindow", "Run"))
        self.editSourceButton.setText(_translate("MasterWindow", "Edit Source"))
        self.settingsButton.setText(_translate("MasterWindow", "Settings"))
        self.menuFile.setTitle(_translate("MasterWindow", "File"))
        self.actionOpen.setText(_translate("MasterWindow", "Open"))
        self.actionSave.setText(_translate("MasterWindow", "Save"))
        self.actionNew.setText(_translate("MasterWindow", "New"))
        self.actionExit.setText(_translate("MasterWindow", "Exit"))
        self.actionSave_As.setText(_translate("MasterWindow", "Save As"))

from pyqtgraph import PlotWidget
