# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_AchromatDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AchromatDialog(object):
    def setupUi(self, AchromatDialog):
        AchromatDialog.setObjectName("AchromatDialog")
        AchromatDialog.resize(737, 685)
        self.achromatButtonBox = QtWidgets.QDialogButtonBox(AchromatDialog)
        self.achromatButtonBox.setGeometry(QtCore.QRect(380, 640, 341, 32))
        self.achromatButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.achromatButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.achromatButtonBox.setObjectName("achromatButtonBox")
        self.nameBox = QtWidgets.QLineEdit(AchromatDialog)
        self.nameBox.setGeometry(QtCore.QRect(190, 60, 521, 27))
        self.nameBox.setObjectName("nameBox")
        self.positionBox = QtWidgets.QLineEdit(AchromatDialog)
        self.positionBox.setGeometry(QtCore.QRect(188, 100, 113, 27))
        self.positionBox.setObjectName("positionBox")
        self.radiusBox = QtWidgets.QLineEdit(AchromatDialog)
        self.radiusBox.setGeometry(QtCore.QRect(450, 100, 121, 27))
        self.radiusBox.setObjectName("radiusBox")
        self.refrind1Box = QtWidgets.QLineEdit(AchromatDialog)
        self.refrind1Box.setGeometry(QtCore.QRect(188, 130, 113, 27))
        self.refrind1Box.setObjectName("refrind1Box")
        self.refrind2Box = QtWidgets.QLineEdit(AchromatDialog)
        self.refrind2Box.setGeometry(QtCore.QRect(450, 130, 121, 27))
        self.refrind2Box.setObjectName("refrind2Box")
        self.label_10 = QtWidgets.QLabel(AchromatDialog)
        self.label_10.setGeometry(QtCore.QRect(60, 70, 52, 15))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(AchromatDialog)
        self.label_11.setGeometry(QtCore.QRect(60, 110, 52, 15))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(AchromatDialog)
        self.label_12.setGeometry(QtCore.QRect(60, 140, 111, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(AchromatDialog)
        self.label_13.setGeometry(QtCore.QRect(320, 100, 52, 15))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(AchromatDialog)
        self.label_14.setGeometry(QtCore.QRect(320, 130, 111, 16))
        self.label_14.setObjectName("label_14")
        self.loadButton = QtWidgets.QPushButton(AchromatDialog)
        self.loadButton.setGeometry(QtCore.QRect(130, 20, 85, 27))
        self.loadButton.setObjectName("loadButton")
        self.saveButton = QtWidgets.QPushButton(AchromatDialog)
        self.saveButton.setGeometry(QtCore.QRect(40, 20, 85, 27))
        self.saveButton.setObjectName("saveButton")
        self.saveloadBox = QtWidgets.QLineEdit(AchromatDialog)
        self.saveloadBox.setGeometry(QtCore.QRect(222, 20, 491, 27))
        self.saveloadBox.setObjectName("saveloadBox")
        self.surface1Combo = QtWidgets.QComboBox(AchromatDialog)
        self.surface1Combo.setGeometry(QtCore.QRect(50, 200, 161, 25))
        self.surface1Combo.setObjectName("surface1Combo")
        self.surface1Combo.addItem("")
        self.surface1Combo.addItem("")
        self.label_15 = QtWidgets.QLabel(AchromatDialog)
        self.label_15.setGeometry(QtCore.QRect(100, 170, 61, 21))
        self.label_15.setObjectName("label_15")
        self.surface2Combo = QtWidgets.QComboBox(AchromatDialog)
        self.surface2Combo.setGeometry(QtCore.QRect(270, 200, 161, 25))
        self.surface2Combo.setObjectName("surface2Combo")
        self.surface2Combo.addItem("")
        self.surface2Combo.addItem("")
        self.label_16 = QtWidgets.QLabel(AchromatDialog)
        self.label_16.setGeometry(QtCore.QRect(320, 170, 61, 21))
        self.label_16.setObjectName("label_16")
        self.surface3Combo = QtWidgets.QComboBox(AchromatDialog)
        self.surface3Combo.setGeometry(QtCore.QRect(490, 200, 161, 25))
        self.surface3Combo.setObjectName("surface3Combo")
        self.surface3Combo.addItem("")
        self.surface3Combo.addItem("")
        self.label_17 = QtWidgets.QLabel(AchromatDialog)
        self.label_17.setGeometry(QtCore.QRect(540, 170, 61, 21))
        self.label_17.setObjectName("label_17")
        self.surface1AsphereFrame = QtWidgets.QFrame(AchromatDialog)
        self.surface1AsphereFrame.setGeometry(QtCore.QRect(30, 240, 201, 381))
        self.surface1AsphereFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.surface1AsphereFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.surface1AsphereFrame.setObjectName("surface1AsphereFrame")
        self.radius1Box = QtWidgets.QLineEdit(self.surface1AsphereFrame)
        self.radius1Box.setGeometry(QtCore.QRect(70, 10, 113, 27))
        self.radius1Box.setObjectName("radius1Box")
        self.scale1Box = QtWidgets.QLineEdit(self.surface1AsphereFrame)
        self.scale1Box.setGeometry(QtCore.QRect(70, 50, 113, 27))
        self.scale1Box.setObjectName("scale1Box")
        self.offset1Box = QtWidgets.QLineEdit(self.surface1AsphereFrame)
        self.offset1Box.setGeometry(QtCore.QRect(70, 90, 113, 27))
        self.offset1Box.setObjectName("offset1Box")
        self.label_2 = QtWidgets.QLabel(self.surface1AsphereFrame)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 52, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.surface1AsphereFrame)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 52, 15))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.surface1AsphereFrame)
        self.label.setGeometry(QtCore.QRect(20, 10, 52, 15))
        self.label.setObjectName("label")
        self.kBox1 = QtWidgets.QLineEdit(self.surface1AsphereFrame)
        self.kBox1.setGeometry(QtCore.QRect(70, 140, 113, 29))
        self.kBox1.setObjectName("kBox1")
        self.a4Box1 = QtWidgets.QLineEdit(self.surface1AsphereFrame)
        self.a4Box1.setGeometry(QtCore.QRect(70, 180, 113, 29))
        self.a4Box1.setObjectName("a4Box1")
        self.a6Box1 = QtWidgets.QLineEdit(self.surface1AsphereFrame)
        self.a6Box1.setGeometry(QtCore.QRect(70, 220, 113, 29))
        self.a6Box1.setObjectName("a6Box1")
        self.a8Box1 = QtWidgets.QLineEdit(self.surface1AsphereFrame)
        self.a8Box1.setGeometry(QtCore.QRect(70, 260, 113, 29))
        self.a8Box1.setObjectName("a8Box1")
        self.a10Box1 = QtWidgets.QLineEdit(self.surface1AsphereFrame)
        self.a10Box1.setGeometry(QtCore.QRect(70, 300, 113, 29))
        self.a10Box1.setObjectName("a10Box1")
        self.a12Box1 = QtWidgets.QLineEdit(self.surface1AsphereFrame)
        self.a12Box1.setGeometry(QtCore.QRect(70, 340, 113, 29))
        self.a12Box1.setObjectName("a12Box1")
        self.label_21 = QtWidgets.QLabel(self.surface1AsphereFrame)
        self.label_21.setGeometry(QtCore.QRect(20, 140, 21, 17))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.surface1AsphereFrame)
        self.label_22.setGeometry(QtCore.QRect(20, 180, 21, 17))
        self.label_22.setObjectName("label_22")
        self.f = QtWidgets.QLabel(self.surface1AsphereFrame)
        self.f.setGeometry(QtCore.QRect(20, 220, 21, 17))
        self.f.setObjectName("f")
        self.label_23 = QtWidgets.QLabel(self.surface1AsphereFrame)
        self.label_23.setGeometry(QtCore.QRect(20, 260, 21, 17))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.surface1AsphereFrame)
        self.label_24.setGeometry(QtCore.QRect(20, 300, 21, 17))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.surface1AsphereFrame)
        self.label_25.setGeometry(QtCore.QRect(20, 340, 21, 17))
        self.label_25.setObjectName("label_25")
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.radius1Box.raise_()
        self.scale1Box.raise_()
        self.offset1Box.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.kBox1.raise_()
        self.a4Box1.raise_()
        self.a6Box1.raise_()
        self.a8Box1.raise_()
        self.a10Box1.raise_()
        self.a12Box1.raise_()
        self.f.raise_()
        self.surface2AsphereFrame = QtWidgets.QFrame(AchromatDialog)
        self.surface2AsphereFrame.setGeometry(QtCore.QRect(250, 240, 201, 381))
        self.surface2AsphereFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.surface2AsphereFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.surface2AsphereFrame.setObjectName("surface2AsphereFrame")
        self.radius2Box = QtWidgets.QLineEdit(self.surface2AsphereFrame)
        self.radius2Box.setGeometry(QtCore.QRect(70, 10, 113, 27))
        self.radius2Box.setObjectName("radius2Box")
        self.scale2Box = QtWidgets.QLineEdit(self.surface2AsphereFrame)
        self.scale2Box.setGeometry(QtCore.QRect(70, 50, 113, 27))
        self.scale2Box.setObjectName("scale2Box")
        self.offset2Box = QtWidgets.QLineEdit(self.surface2AsphereFrame)
        self.offset2Box.setGeometry(QtCore.QRect(70, 90, 113, 27))
        self.offset2Box.setObjectName("offset2Box")
        self.label_4 = QtWidgets.QLabel(self.surface2AsphereFrame)
        self.label_4.setGeometry(QtCore.QRect(20, 50, 52, 15))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.surface2AsphereFrame)
        self.label_5.setGeometry(QtCore.QRect(20, 90, 52, 15))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.surface2AsphereFrame)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 52, 15))
        self.label_6.setObjectName("label_6")
        self.kBox2 = QtWidgets.QLineEdit(self.surface2AsphereFrame)
        self.kBox2.setGeometry(QtCore.QRect(70, 140, 113, 29))
        self.kBox2.setObjectName("kBox2")
        self.a4Box2 = QtWidgets.QLineEdit(self.surface2AsphereFrame)
        self.a4Box2.setGeometry(QtCore.QRect(70, 180, 113, 29))
        self.a4Box2.setObjectName("a4Box2")
        self.a6Box2 = QtWidgets.QLineEdit(self.surface2AsphereFrame)
        self.a6Box2.setGeometry(QtCore.QRect(70, 220, 113, 29))
        self.a6Box2.setObjectName("a6Box2")
        self.a8Box2 = QtWidgets.QLineEdit(self.surface2AsphereFrame)
        self.a8Box2.setGeometry(QtCore.QRect(70, 260, 113, 29))
        self.a8Box2.setObjectName("a8Box2")
        self.a10Box2 = QtWidgets.QLineEdit(self.surface2AsphereFrame)
        self.a10Box2.setGeometry(QtCore.QRect(70, 300, 113, 29))
        self.a10Box2.setObjectName("a10Box2")
        self.a12Box2 = QtWidgets.QLineEdit(self.surface2AsphereFrame)
        self.a12Box2.setGeometry(QtCore.QRect(70, 340, 113, 29))
        self.a12Box2.setObjectName("a12Box2")
        self.label_26 = QtWidgets.QLabel(self.surface2AsphereFrame)
        self.label_26.setGeometry(QtCore.QRect(20, 140, 21, 17))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.surface2AsphereFrame)
        self.label_27.setGeometry(QtCore.QRect(20, 180, 21, 17))
        self.label_27.setObjectName("label_27")
        self.f_2 = QtWidgets.QLabel(self.surface2AsphereFrame)
        self.f_2.setGeometry(QtCore.QRect(20, 220, 21, 17))
        self.f_2.setObjectName("f_2")
        self.label_28 = QtWidgets.QLabel(self.surface2AsphereFrame)
        self.label_28.setGeometry(QtCore.QRect(20, 260, 21, 17))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.surface2AsphereFrame)
        self.label_29.setGeometry(QtCore.QRect(20, 300, 21, 17))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.surface2AsphereFrame)
        self.label_30.setGeometry(QtCore.QRect(20, 340, 21, 17))
        self.label_30.setObjectName("label_30")
        self.surface3AsphereFrame = QtWidgets.QFrame(AchromatDialog)
        self.surface3AsphereFrame.setGeometry(QtCore.QRect(470, 240, 201, 381))
        self.surface3AsphereFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.surface3AsphereFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.surface3AsphereFrame.setObjectName("surface3AsphereFrame")
        self.radius3Box = QtWidgets.QLineEdit(self.surface3AsphereFrame)
        self.radius3Box.setGeometry(QtCore.QRect(70, 10, 113, 27))
        self.radius3Box.setObjectName("radius3Box")
        self.scale3Box = QtWidgets.QLineEdit(self.surface3AsphereFrame)
        self.scale3Box.setGeometry(QtCore.QRect(70, 50, 113, 27))
        self.scale3Box.setObjectName("scale3Box")
        self.offset3Box = QtWidgets.QLineEdit(self.surface3AsphereFrame)
        self.offset3Box.setGeometry(QtCore.QRect(70, 90, 113, 27))
        self.offset3Box.setObjectName("offset3Box")
        self.label_7 = QtWidgets.QLabel(self.surface3AsphereFrame)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 52, 15))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.surface3AsphereFrame)
        self.label_8.setGeometry(QtCore.QRect(20, 90, 52, 15))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.surface3AsphereFrame)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 52, 15))
        self.label_9.setObjectName("label_9")
        self.kBox3 = QtWidgets.QLineEdit(self.surface3AsphereFrame)
        self.kBox3.setGeometry(QtCore.QRect(70, 140, 113, 29))
        self.kBox3.setObjectName("kBox3")
        self.a4Box3 = QtWidgets.QLineEdit(self.surface3AsphereFrame)
        self.a4Box3.setGeometry(QtCore.QRect(70, 180, 113, 29))
        self.a4Box3.setObjectName("a4Box3")
        self.a6Box3 = QtWidgets.QLineEdit(self.surface3AsphereFrame)
        self.a6Box3.setGeometry(QtCore.QRect(70, 220, 113, 29))
        self.a6Box3.setObjectName("a6Box3")
        self.a8Box3 = QtWidgets.QLineEdit(self.surface3AsphereFrame)
        self.a8Box3.setGeometry(QtCore.QRect(70, 260, 113, 29))
        self.a8Box3.setObjectName("a8Box3")
        self.a10Box3 = QtWidgets.QLineEdit(self.surface3AsphereFrame)
        self.a10Box3.setGeometry(QtCore.QRect(70, 300, 113, 29))
        self.a10Box3.setObjectName("a10Box3")
        self.a12Box3 = QtWidgets.QLineEdit(self.surface3AsphereFrame)
        self.a12Box3.setGeometry(QtCore.QRect(70, 340, 113, 29))
        self.a12Box3.setObjectName("a12Box3")
        self.label_31 = QtWidgets.QLabel(self.surface3AsphereFrame)
        self.label_31.setGeometry(QtCore.QRect(20, 140, 21, 17))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.surface3AsphereFrame)
        self.label_32.setGeometry(QtCore.QRect(20, 180, 21, 17))
        self.label_32.setObjectName("label_32")
        self.f_3 = QtWidgets.QLabel(self.surface3AsphereFrame)
        self.f_3.setGeometry(QtCore.QRect(20, 220, 21, 17))
        self.f_3.setObjectName("f_3")
        self.label_33 = QtWidgets.QLabel(self.surface3AsphereFrame)
        self.label_33.setGeometry(QtCore.QRect(20, 260, 21, 17))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.surface3AsphereFrame)
        self.label_34.setGeometry(QtCore.QRect(20, 300, 21, 17))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.surface3AsphereFrame)
        self.label_35.setGeometry(QtCore.QRect(20, 340, 21, 17))
        self.label_35.setObjectName("label_35")
        self.radius3Box.raise_()
        self.scale3Box.raise_()
        self.offset3Box.raise_()
        self.label_9.raise_()
        self.kBox3.raise_()
        self.a4Box3.raise_()
        self.a6Box3.raise_()
        self.a8Box3.raise_()
        self.a10Box3.raise_()
        self.a12Box3.raise_()
        self.label_31.raise_()
        self.label_32.raise_()
        self.f_3.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.flipButton = QtWidgets.QPushButton(AchromatDialog)
        self.flipButton.setGeometry(QtCore.QRect(610, 120, 85, 27))
        self.flipButton.setObjectName("flipButton")
        self.surface1FlatFrame = QtWidgets.QFrame(AchromatDialog)
        self.surface1FlatFrame.setGeometry(QtCore.QRect(30, 240, 201, 131))
        self.surface1FlatFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.surface1FlatFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.surface1FlatFrame.setObjectName("surface1FlatFrame")
        self.thickness1Box = QtWidgets.QLineEdit(self.surface1FlatFrame)
        self.thickness1Box.setGeometry(QtCore.QRect(70, 10, 113, 27))
        self.thickness1Box.setObjectName("thickness1Box")
        self.label_18 = QtWidgets.QLabel(self.surface1FlatFrame)
        self.label_18.setGeometry(QtCore.QRect(20, 10, 41, 16))
        self.label_18.setObjectName("label_18")
        self.thickness1Box.raise_()
        self.label_18.raise_()
        self.surface1AsphereFrame.raise_()
        self.surface2FlatFrame = QtWidgets.QFrame(AchromatDialog)
        self.surface2FlatFrame.setGeometry(QtCore.QRect(250, 240, 201, 131))
        self.surface2FlatFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.surface2FlatFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.surface2FlatFrame.setObjectName("surface2FlatFrame")
        self.thickness2Box = QtWidgets.QLineEdit(self.surface2FlatFrame)
        self.thickness2Box.setGeometry(QtCore.QRect(70, 10, 113, 27))
        self.thickness2Box.setObjectName("thickness2Box")
        self.label_19 = QtWidgets.QLabel(self.surface2FlatFrame)
        self.label_19.setGeometry(QtCore.QRect(20, 10, 41, 16))
        self.label_19.setObjectName("label_19")
        self.surface3FlatFrame = QtWidgets.QFrame(AchromatDialog)
        self.surface3FlatFrame.setGeometry(QtCore.QRect(470, 240, 201, 131))
        self.surface3FlatFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.surface3FlatFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.surface3FlatFrame.setObjectName("surface3FlatFrame")
        self.thickness3Box = QtWidgets.QLineEdit(self.surface3FlatFrame)
        self.thickness3Box.setGeometry(QtCore.QRect(70, 10, 113, 27))
        self.thickness3Box.setObjectName("thickness3Box")
        self.label_20 = QtWidgets.QLabel(self.surface3FlatFrame)
        self.label_20.setGeometry(QtCore.QRect(20, 10, 41, 16))
        self.label_20.setObjectName("label_20")

        self.retranslateUi(AchromatDialog)
        self.surface1Combo.setCurrentIndex(0)
        self.surface2Combo.setCurrentIndex(0)
        self.surface3Combo.setCurrentIndex(0)
        self.achromatButtonBox.accepted.connect(AchromatDialog.accept)
        self.achromatButtonBox.rejected.connect(AchromatDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AchromatDialog)
        AchromatDialog.setTabOrder(self.nameBox, self.positionBox)
        AchromatDialog.setTabOrder(self.positionBox, self.radiusBox)
        AchromatDialog.setTabOrder(self.radiusBox, self.refrind1Box)
        AchromatDialog.setTabOrder(self.refrind1Box, self.refrind2Box)
        AchromatDialog.setTabOrder(self.refrind2Box, self.achromatButtonBox)

    def retranslateUi(self, AchromatDialog):
        _translate = QtCore.QCoreApplication.translate
        AchromatDialog.setWindowTitle(_translate("AchromatDialog", "Achromat"))
        self.label_10.setText(_translate("AchromatDialog", "Name"))
        self.label_11.setText(_translate("AchromatDialog", "Position"))
        self.label_12.setText(_translate("AchromatDialog", "Refractive Index 1"))
        self.label_13.setText(_translate("AchromatDialog", "Radius"))
        self.label_14.setText(_translate("AchromatDialog", "Refractive Index 2"))
        self.loadButton.setText(_translate("AchromatDialog", "Load"))
        self.saveButton.setText(_translate("AchromatDialog", "File"))
        self.surface1Combo.setItemText(0, _translate("AchromatDialog", "Asphere"))
        self.surface1Combo.setItemText(1, _translate("AchromatDialog", "Flat"))
        self.label_15.setText(_translate("AchromatDialog", "Surface 1"))
        self.surface2Combo.setItemText(0, _translate("AchromatDialog", "Asphere"))
        self.surface2Combo.setItemText(1, _translate("AchromatDialog", "Flat"))
        self.label_16.setText(_translate("AchromatDialog", "Surface 2"))
        self.surface3Combo.setItemText(0, _translate("AchromatDialog", "Asphere"))
        self.surface3Combo.setItemText(1, _translate("AchromatDialog", "Flat"))
        self.label_17.setText(_translate("AchromatDialog", "Surface 2"))
        self.label_2.setText(_translate("AchromatDialog", "Scale"))
        self.label_3.setText(_translate("AchromatDialog", "Offset"))
        self.label.setText(_translate("AchromatDialog", "Radius"))
        self.kBox1.setText(_translate("AchromatDialog", "0"))
        self.a4Box1.setText(_translate("AchromatDialog", "0"))
        self.a6Box1.setText(_translate("AchromatDialog", "0"))
        self.a8Box1.setText(_translate("AchromatDialog", "0"))
        self.a10Box1.setText(_translate("AchromatDialog", "0"))
        self.a12Box1.setText(_translate("AchromatDialog", "0"))
        self.label_21.setText(_translate("AchromatDialog", "k"))
        self.label_22.setText(_translate("AchromatDialog", "a4"))
        self.f.setText(_translate("AchromatDialog", "a6"))
        self.label_23.setText(_translate("AchromatDialog", "a8"))
        self.label_24.setText(_translate("AchromatDialog", "a10"))
        self.label_25.setText(_translate("AchromatDialog", "a12"))
        self.label_4.setText(_translate("AchromatDialog", "Scale"))
        self.label_5.setText(_translate("AchromatDialog", "Offset"))
        self.label_6.setText(_translate("AchromatDialog", "Radius"))
        self.kBox2.setText(_translate("AchromatDialog", "0"))
        self.a4Box2.setText(_translate("AchromatDialog", "0"))
        self.a6Box2.setText(_translate("AchromatDialog", "0"))
        self.a8Box2.setText(_translate("AchromatDialog", "0"))
        self.a10Box2.setText(_translate("AchromatDialog", "0"))
        self.a12Box2.setText(_translate("AchromatDialog", "0"))
        self.label_26.setText(_translate("AchromatDialog", "k"))
        self.label_27.setText(_translate("AchromatDialog", "a4"))
        self.f_2.setText(_translate("AchromatDialog", "a6"))
        self.label_28.setText(_translate("AchromatDialog", "a8"))
        self.label_29.setText(_translate("AchromatDialog", "a10"))
        self.label_30.setText(_translate("AchromatDialog", "a12"))
        self.label_7.setText(_translate("AchromatDialog", "Scale"))
        self.label_8.setText(_translate("AchromatDialog", "Offset"))
        self.label_9.setText(_translate("AchromatDialog", "Radius"))
        self.kBox3.setText(_translate("AchromatDialog", "0"))
        self.a4Box3.setText(_translate("AchromatDialog", "0"))
        self.a6Box3.setText(_translate("AchromatDialog", "0"))
        self.a8Box3.setText(_translate("AchromatDialog", "0"))
        self.a10Box3.setText(_translate("AchromatDialog", "0"))
        self.a12Box3.setText(_translate("AchromatDialog", "0"))
        self.label_31.setText(_translate("AchromatDialog", "k"))
        self.label_32.setText(_translate("AchromatDialog", "a4"))
        self.f_3.setText(_translate("AchromatDialog", "a6"))
        self.label_33.setText(_translate("AchromatDialog", "a8"))
        self.label_34.setText(_translate("AchromatDialog", "a10"))
        self.label_35.setText(_translate("AchromatDialog", "a12"))
        self.flipButton.setText(_translate("AchromatDialog", "Flip"))
        self.label_18.setText(_translate("AchromatDialog", "Offset"))
        self.label_19.setText(_translate("AchromatDialog", "Offset"))
        self.label_20.setText(_translate("AchromatDialog", "Offset"))

