# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_LensDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LensDialog(object):
    def setupUi(self, LensDialog):
        LensDialog.setObjectName("LensDialog")
        LensDialog.resize(738, 629)
        self.lensButtonBox = QtWidgets.QDialogButtonBox(LensDialog)
        self.lensButtonBox.setGeometry(QtCore.QRect(360, 570, 341, 32))
        self.lensButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.lensButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.lensButtonBox.setObjectName("lensButtonBox")
        self.nameBox = QtWidgets.QLineEdit(LensDialog)
        self.nameBox.setGeometry(QtCore.QRect(140, 60, 561, 27))
        self.nameBox.setObjectName("nameBox")
        self.label_11 = QtWidgets.QLabel(LensDialog)
        self.label_11.setGeometry(QtCore.QRect(50, 110, 52, 15))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(LensDialog)
        self.label_12.setGeometry(QtCore.QRect(470, 110, 111, 16))
        self.label_12.setObjectName("label_12")
        self.positionBox = QtWidgets.QLineEdit(LensDialog)
        self.positionBox.setGeometry(QtCore.QRect(140, 100, 113, 27))
        self.positionBox.setObjectName("positionBox")
        self.refrindBox = QtWidgets.QLineEdit(LensDialog)
        self.refrindBox.setGeometry(QtCore.QRect(590, 100, 113, 27))
        self.refrindBox.setObjectName("refrindBox")
        self.radiusBox = QtWidgets.QLineEdit(LensDialog)
        self.radiusBox.setGeometry(QtCore.QRect(320, 100, 121, 27))
        self.radiusBox.setObjectName("radiusBox")
        self.label_10 = QtWidgets.QLabel(LensDialog)
        self.label_10.setGeometry(QtCore.QRect(50, 70, 52, 15))
        self.label_10.setObjectName("label_10")
        self.label_13 = QtWidgets.QLabel(LensDialog)
        self.label_13.setGeometry(QtCore.QRect(270, 110, 52, 15))
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(LensDialog)
        self.label_15.setGeometry(QtCore.QRect(110, 150, 61, 21))
        self.label_15.setObjectName("label_15")
        self.surface1Combo = QtWidgets.QComboBox(LensDialog)
        self.surface1Combo.setGeometry(QtCore.QRect(60, 180, 161, 25))
        self.surface1Combo.setObjectName("surface1Combo")
        self.surface1Combo.addItem("")
        self.surface1Combo.addItem("")
        self.surface1AsphereFrame = QtWidgets.QFrame(LensDialog)
        self.surface1AsphereFrame.setGeometry(QtCore.QRect(40, 220, 201, 381))
        self.surface1AsphereFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.surface1AsphereFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.surface1AsphereFrame.setObjectName("surface1AsphereFrame")
        self.radius1Box = QtWidgets.QLineEdit(self.surface1AsphereFrame)
        self.radius1Box.setGeometry(QtCore.QRect(70, 10, 113, 27))
        self.radius1Box.setObjectName("radius1Box")
        self.scale1Box = QtWidgets.QLineEdit(self.surface1AsphereFrame)
        self.scale1Box.setGeometry(QtCore.QRect(70, 50, 113, 27))
        self.scale1Box.setObjectName("scale1Box")
        self.offset1Box = QtWidgets.QLineEdit(self.surface1AsphereFrame)
        self.offset1Box.setGeometry(QtCore.QRect(70, 90, 113, 27))
        self.offset1Box.setObjectName("offset1Box")
        self.label_2 = QtWidgets.QLabel(self.surface1AsphereFrame)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 52, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.surface1AsphereFrame)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 52, 15))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.surface1AsphereFrame)
        self.label.setGeometry(QtCore.QRect(20, 10, 52, 15))
        self.label.setObjectName("label")
        self.kBox1 = QtWidgets.QLineEdit(self.surface1AsphereFrame)
        self.kBox1.setGeometry(QtCore.QRect(70, 140, 113, 29))
        self.kBox1.setObjectName("kBox1")
        self.a4Box1 = QtWidgets.QLineEdit(self.surface1AsphereFrame)
        self.a4Box1.setGeometry(QtCore.QRect(70, 180, 113, 29))
        self.a4Box1.setObjectName("a4Box1")
        self.a6Box1 = QtWidgets.QLineEdit(self.surface1AsphereFrame)
        self.a6Box1.setGeometry(QtCore.QRect(70, 220, 113, 29))
        self.a6Box1.setObjectName("a6Box1")
        self.a8Box1 = QtWidgets.QLineEdit(self.surface1AsphereFrame)
        self.a8Box1.setGeometry(QtCore.QRect(70, 260, 113, 29))
        self.a8Box1.setObjectName("a8Box1")
        self.a10Box1 = QtWidgets.QLineEdit(self.surface1AsphereFrame)
        self.a10Box1.setGeometry(QtCore.QRect(70, 300, 113, 29))
        self.a10Box1.setObjectName("a10Box1")
        self.a12Box1 = QtWidgets.QLineEdit(self.surface1AsphereFrame)
        self.a12Box1.setGeometry(QtCore.QRect(70, 340, 113, 29))
        self.a12Box1.setObjectName("a12Box1")
        self.label_7 = QtWidgets.QLabel(self.surface1AsphereFrame)
        self.label_7.setGeometry(QtCore.QRect(20, 140, 21, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.surface1AsphereFrame)
        self.label_8.setGeometry(QtCore.QRect(20, 180, 21, 17))
        self.label_8.setObjectName("label_8")
        self.f = QtWidgets.QLabel(self.surface1AsphereFrame)
        self.f.setGeometry(QtCore.QRect(20, 220, 21, 17))
        self.f.setObjectName("f")
        self.label_14 = QtWidgets.QLabel(self.surface1AsphereFrame)
        self.label_14.setGeometry(QtCore.QRect(20, 260, 21, 17))
        self.label_14.setObjectName("label_14")
        self.label_17 = QtWidgets.QLabel(self.surface1AsphereFrame)
        self.label_17.setGeometry(QtCore.QRect(20, 300, 21, 17))
        self.label_17.setObjectName("label_17")
        self.label_20 = QtWidgets.QLabel(self.surface1AsphereFrame)
        self.label_20.setGeometry(QtCore.QRect(20, 340, 21, 17))
        self.label_20.setObjectName("label_20")
        self.surface1FlatFrame = QtWidgets.QFrame(LensDialog)
        self.surface1FlatFrame.setGeometry(QtCore.QRect(40, 220, 201, 131))
        self.surface1FlatFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.surface1FlatFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.surface1FlatFrame.setObjectName("surface1FlatFrame")
        self.thickness1Box = QtWidgets.QLineEdit(self.surface1FlatFrame)
        self.thickness1Box.setGeometry(QtCore.QRect(70, 10, 113, 27))
        self.thickness1Box.setObjectName("thickness1Box")
        self.label_18 = QtWidgets.QLabel(self.surface1FlatFrame)
        self.label_18.setGeometry(QtCore.QRect(20, 10, 41, 16))
        self.label_18.setObjectName("label_18")
        self.surface2Combo = QtWidgets.QComboBox(LensDialog)
        self.surface2Combo.setGeometry(QtCore.QRect(290, 180, 161, 25))
        self.surface2Combo.setObjectName("surface2Combo")
        self.surface2Combo.addItem("")
        self.surface2Combo.addItem("")
        self.label_16 = QtWidgets.QLabel(LensDialog)
        self.label_16.setGeometry(QtCore.QRect(340, 150, 61, 21))
        self.label_16.setObjectName("label_16")
        self.surface2FlatFrame = QtWidgets.QFrame(LensDialog)
        self.surface2FlatFrame.setGeometry(QtCore.QRect(270, 220, 201, 131))
        self.surface2FlatFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.surface2FlatFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.surface2FlatFrame.setObjectName("surface2FlatFrame")
        self.thickness2Box = QtWidgets.QLineEdit(self.surface2FlatFrame)
        self.thickness2Box.setGeometry(QtCore.QRect(70, 10, 113, 27))
        self.thickness2Box.setObjectName("thickness2Box")
        self.label_19 = QtWidgets.QLabel(self.surface2FlatFrame)
        self.label_19.setGeometry(QtCore.QRect(20, 10, 41, 16))
        self.label_19.setObjectName("label_19")
        self.saveloadBox = QtWidgets.QLineEdit(LensDialog)
        self.saveloadBox.setGeometry(QtCore.QRect(212, 20, 491, 27))
        self.saveloadBox.setObjectName("saveloadBox")
        self.saveButton = QtWidgets.QPushButton(LensDialog)
        self.saveButton.setGeometry(QtCore.QRect(30, 20, 85, 27))
        self.saveButton.setObjectName("saveButton")
        self.loadButton = QtWidgets.QPushButton(LensDialog)
        self.loadButton.setGeometry(QtCore.QRect(120, 20, 85, 27))
        self.loadButton.setObjectName("loadButton")
        self.surface2AsphereFrame = QtWidgets.QFrame(LensDialog)
        self.surface2AsphereFrame.setGeometry(QtCore.QRect(270, 220, 201, 381))
        self.surface2AsphereFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.surface2AsphereFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.surface2AsphereFrame.setObjectName("surface2AsphereFrame")
        self.radius2Box = QtWidgets.QLineEdit(self.surface2AsphereFrame)
        self.radius2Box.setGeometry(QtCore.QRect(70, 10, 113, 27))
        self.radius2Box.setObjectName("radius2Box")
        self.scale2Box = QtWidgets.QLineEdit(self.surface2AsphereFrame)
        self.scale2Box.setGeometry(QtCore.QRect(70, 50, 113, 27))
        self.scale2Box.setObjectName("scale2Box")
        self.offset2Box = QtWidgets.QLineEdit(self.surface2AsphereFrame)
        self.offset2Box.setGeometry(QtCore.QRect(70, 90, 113, 27))
        self.offset2Box.setObjectName("offset2Box")
        self.label_9 = QtWidgets.QLabel(self.surface2AsphereFrame)
        self.label_9.setGeometry(QtCore.QRect(20, 50, 52, 15))
        self.label_9.setObjectName("label_9")
        self.label_21 = QtWidgets.QLabel(self.surface2AsphereFrame)
        self.label_21.setGeometry(QtCore.QRect(20, 90, 52, 15))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.surface2AsphereFrame)
        self.label_22.setGeometry(QtCore.QRect(20, 10, 52, 15))
        self.label_22.setObjectName("label_22")
        self.kBox2 = QtWidgets.QLineEdit(self.surface2AsphereFrame)
        self.kBox2.setGeometry(QtCore.QRect(70, 140, 113, 29))
        self.kBox2.setObjectName("kBox2")
        self.a4Box2 = QtWidgets.QLineEdit(self.surface2AsphereFrame)
        self.a4Box2.setGeometry(QtCore.QRect(70, 180, 113, 29))
        self.a4Box2.setObjectName("a4Box2")
        self.a6Box2 = QtWidgets.QLineEdit(self.surface2AsphereFrame)
        self.a6Box2.setGeometry(QtCore.QRect(70, 220, 113, 29))
        self.a6Box2.setObjectName("a6Box2")
        self.a8Box2 = QtWidgets.QLineEdit(self.surface2AsphereFrame)
        self.a8Box2.setGeometry(QtCore.QRect(70, 260, 113, 29))
        self.a8Box2.setObjectName("a8Box2")
        self.a10Box2 = QtWidgets.QLineEdit(self.surface2AsphereFrame)
        self.a10Box2.setGeometry(QtCore.QRect(70, 300, 113, 29))
        self.a10Box2.setObjectName("a10Box2")
        self.a12Box2 = QtWidgets.QLineEdit(self.surface2AsphereFrame)
        self.a12Box2.setGeometry(QtCore.QRect(70, 340, 113, 29))
        self.a12Box2.setObjectName("a12Box2")
        self.label_23 = QtWidgets.QLabel(self.surface2AsphereFrame)
        self.label_23.setGeometry(QtCore.QRect(20, 140, 21, 17))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.surface2AsphereFrame)
        self.label_24.setGeometry(QtCore.QRect(20, 180, 21, 17))
        self.label_24.setObjectName("label_24")
        self.f_2 = QtWidgets.QLabel(self.surface2AsphereFrame)
        self.f_2.setGeometry(QtCore.QRect(20, 220, 21, 17))
        self.f_2.setObjectName("f_2")
        self.label_25 = QtWidgets.QLabel(self.surface2AsphereFrame)
        self.label_25.setGeometry(QtCore.QRect(20, 260, 21, 17))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.surface2AsphereFrame)
        self.label_26.setGeometry(QtCore.QRect(20, 300, 21, 17))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.surface2AsphereFrame)
        self.label_27.setGeometry(QtCore.QRect(20, 340, 21, 17))
        self.label_27.setObjectName("label_27")
        self.flipButton = QtWidgets.QPushButton(LensDialog)
        self.flipButton.setGeometry(QtCore.QRect(580, 180, 85, 27))
        self.flipButton.setObjectName("flipButton")
        self.surface1AsphereFrame.raise_()
        self.lensButtonBox.raise_()
        self.nameBox.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.positionBox.raise_()
        self.refrindBox.raise_()
        self.radiusBox.raise_()
        self.label_10.raise_()
        self.label_13.raise_()
        self.label_15.raise_()
        self.surface1Combo.raise_()
        self.surface1FlatFrame.raise_()
        self.surface2Combo.raise_()
        self.label_16.raise_()
        self.surface2FlatFrame.raise_()
        self.saveloadBox.raise_()
        self.saveButton.raise_()
        self.loadButton.raise_()
        self.surface2AsphereFrame.raise_()
        self.flipButton.raise_()

        self.retranslateUi(LensDialog)
        self.surface1Combo.setCurrentIndex(0)
        self.surface2Combo.setCurrentIndex(0)
        self.lensButtonBox.accepted.connect(LensDialog.accept)
        self.lensButtonBox.rejected.connect(LensDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(LensDialog)

    def retranslateUi(self, LensDialog):
        _translate = QtCore.QCoreApplication.translate
        LensDialog.setWindowTitle(_translate("LensDialog", "Lens"))
        self.label_11.setText(_translate("LensDialog", "Position"))
        self.label_12.setText(_translate("LensDialog", "Refractive Index"))
        self.label_10.setText(_translate("LensDialog", "Name"))
        self.label_13.setText(_translate("LensDialog", "Radius"))
        self.label_15.setText(_translate("LensDialog", "Surface 1"))
        self.surface1Combo.setItemText(0, _translate("LensDialog", "Asphere"))
        self.surface1Combo.setItemText(1, _translate("LensDialog", "Flat"))
        self.label_2.setText(_translate("LensDialog", "Scale"))
        self.label_3.setText(_translate("LensDialog", "Offset"))
        self.label.setText(_translate("LensDialog", "Radius"))
        self.kBox1.setText(_translate("LensDialog", "0"))
        self.a4Box1.setText(_translate("LensDialog", "0"))
        self.a6Box1.setText(_translate("LensDialog", "0"))
        self.a8Box1.setText(_translate("LensDialog", "0"))
        self.a10Box1.setText(_translate("LensDialog", "0"))
        self.a12Box1.setText(_translate("LensDialog", "0"))
        self.label_7.setText(_translate("LensDialog", "k"))
        self.label_8.setText(_translate("LensDialog", "a4"))
        self.f.setText(_translate("LensDialog", "a6"))
        self.label_14.setText(_translate("LensDialog", "a8"))
        self.label_17.setText(_translate("LensDialog", "a10"))
        self.label_20.setText(_translate("LensDialog", "a12"))
        self.label_18.setText(_translate("LensDialog", "Offset"))
        self.surface2Combo.setItemText(0, _translate("LensDialog", "Asphere"))
        self.surface2Combo.setItemText(1, _translate("LensDialog", "Flat"))
        self.label_16.setText(_translate("LensDialog", "Surface 2"))
        self.label_19.setText(_translate("LensDialog", "Offset"))
        self.saveButton.setText(_translate("LensDialog", "File"))
        self.loadButton.setText(_translate("LensDialog", "Load"))
        self.label_9.setText(_translate("LensDialog", "Scale"))
        self.label_21.setText(_translate("LensDialog", "Offset"))
        self.label_22.setText(_translate("LensDialog", "Radius"))
        self.kBox2.setText(_translate("LensDialog", "0"))
        self.a4Box2.setText(_translate("LensDialog", "0"))
        self.a6Box2.setText(_translate("LensDialog", "0"))
        self.a8Box2.setText(_translate("LensDialog", "0"))
        self.a10Box2.setText(_translate("LensDialog", "0"))
        self.a12Box2.setText(_translate("LensDialog", "0"))
        self.label_23.setText(_translate("LensDialog", "k"))
        self.label_24.setText(_translate("LensDialog", "a4"))
        self.f_2.setText(_translate("LensDialog", "a6"))
        self.label_25.setText(_translate("LensDialog", "a8"))
        self.label_26.setText(_translate("LensDialog", "a10"))
        self.label_27.setText(_translate("LensDialog", "a12"))
        self.flipButton.setText(_translate("LensDialog", "Flip"))

